# Generated by Django 5.2.8 on 2025-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_alter_courses_category_alter_courses_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
