# Generated by Django 5.2.8 on 2025-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessons_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m'),
        ),
    ]
