# Generated by Django 5.2.8 on 2025-11-16 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
